app = 'monthly-py'
primary_region = 'ord'

# [build]
# image = 'ghcr.io/gcca/monthly-py:latest'

[env]
DB_URL = '/app/data/monthly-py.db'
MONTHLY_PY_SESSION_ENCRYPTION_KEY = ''
MONTHLY_PY_O365_CLIENT_ID = ''
MONTHLY_PY_O365_CLIENT_SECRET = ''
MONTHLY_PY_O365_TENANT_ID = ''
MONTHLY_PY_DATABASE_PATH = '/app/data/monthly-py.db'
TZ = 'UTC'

[[mounts]]
source = 'monthly_py_data'
destination = '/app/data'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = 'requests'
hard_limit = 100
soft_limit = 80

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
